import {
  APPS_KEY,
  CLIENTES_KEY,
  EVENTOS_KEY,
  HORARIOS_KEY,
  NOTICIAS_KEY,
  OBJETIVOS_KEY,
  PERMISOS_KEY,
  ROLES_KEY,
  USUARIOS_KEY,
  VACACIONES_KEY
} from './keys';

export const STORAGE_LOGOS_CLIENTES_PATH = CLIENTES_KEY;
export const STORAGE_DOCS_CLIENTES_PATH = `${CLIENTES_KEY}Docs`;
export const STORAGE_NOTICIAS_PATH = NOTICIAS_KEY;
export const STORAGE_APPS_PATH = APPS_KEY;

export const FIRESTORE_USUARIOS_PATH = USUARIOS_KEY;
export const FIRESTORE_CLIENTES_PATH = CLIENTES_KEY;
export const FIRESTORE_ROLES_PATH = ROLES_KEY;
export const FIRESTORE_PERMISOS_PATH = PERMISOS_KEY;
export const FIRESTORE_NOTICIAS_PATH = NOTICIAS_KEY;
export const FIRESTORE_APPS_PATH = APPS_KEY;
export const FIRESTORE_EVENTOS_PATH = EVENTOS_KEY;
export const FIRESTORE_OBJETIVOS_PATH = OBJETIVOS_KEY;
export const FIRESTORE_HORARIOS_PATH = HORARIOS_KEY;
export const FIRESTORE_VACACIONES_PATH = VACACIONES_KEY;
