/* CRUD CATEGORIES */
export const ACCESO_CATEGORY_KEY = 'acceso';
export const CREAR_CATEGORY_KEY = 'crear';
export const EDITAR_CATEGORY_KEY = 'editar';
export const ELIMINAR_CATEGORY_KEY = 'eliminar';
export const INACTIVAR_CATEGORY_KEY = 'inactivar';
export const APROBAR_CATEGORY_KEY = 'aprobar';
export const ASIGNAR_CATEGORY_KEY = 'asignar';
export const EVALUAR_CATEGORY_KEY = 'evaluar';
/* FUNCTIONS SUBCATEGORIES */
export const USUARIOS_SUBCATEGORY_KEY = 'usuarios';
export const CLIENTES_SUBCATEGORY_KEY = 'clientes';
export const NOTICIAS_SUBCATEGORY_KEY = 'noticias';
export const APPS_SUBCATEGORY_KEY = 'apps';
export const ROLES_SUBCATEGORY_KEY = 'roles';
export const EVENTOS_SUBCATEGORY_KEY = 'eventos';
export const HORARIOS_SUBCATEGORY_KEY = 'horarios';
export const VACACIONES_SUBCATEGORY_KEY = 'vacaciones';
export const REPORTES_SUBCATEGORY_KEY = 'reportes';
export const OBJETIVOS_SUBCATEGORY_KEY = 'objetivos';
export const REGISTROS_SUBCATEGORY_KEY = 'registros';

export const PERMISOS_MAP_IDS = {
  /* DE ACCESO */
  accesoRoles: `${ACCESO_CATEGORY_KEY}-${ROLES_SUBCATEGORY_KEY}`,
  accesoClientes: `${ACCESO_CATEGORY_KEY}-${CLIENTES_SUBCATEGORY_KEY}`,
  accesoUsuarios: `${ACCESO_CATEGORY_KEY}-${USUARIOS_SUBCATEGORY_KEY}`,
  accesoNoticias: `${ACCESO_CATEGORY_KEY}-${NOTICIAS_SUBCATEGORY_KEY}`,
  accesoApps: `${ACCESO_CATEGORY_KEY}-${APPS_SUBCATEGORY_KEY}`,
  accesoHorarios: `${ACCESO_CATEGORY_KEY}-${HORARIOS_SUBCATEGORY_KEY}`,
  accesoEventos: `${ACCESO_CATEGORY_KEY}-${EVENTOS_SUBCATEGORY_KEY}`,
  accesoVacaciones: `${ACCESO_CATEGORY_KEY}-${VACACIONES_SUBCATEGORY_KEY}`,
  accesoReportes: `${ACCESO_CATEGORY_KEY}-${REPORTES_SUBCATEGORY_KEY}`,
  accesoObjetivos: `${ACCESO_CATEGORY_KEY}-${OBJETIVOS_SUBCATEGORY_KEY}`,
  accesoRegistros: `${ACCESO_CATEGORY_KEY}-${REGISTROS_SUBCATEGORY_KEY}`,
  /* DE CREAR */
  crearUsuarios: `${CREAR_CATEGORY_KEY}-${USUARIOS_SUBCATEGORY_KEY}`,
  crearClientes: `${CREAR_CATEGORY_KEY}-${CLIENTES_SUBCATEGORY_KEY}`,
  crearRoles: `${CREAR_CATEGORY_KEY}-${ROLES_SUBCATEGORY_KEY}`,
  crearNoticias: `${CREAR_CATEGORY_KEY}-${NOTICIAS_SUBCATEGORY_KEY}`,
  crearApps: `${CREAR_CATEGORY_KEY}-${APPS_SUBCATEGORY_KEY}`,
  crearHorarios: `${CREAR_CATEGORY_KEY}-${HORARIOS_SUBCATEGORY_KEY}`,
  crearEventos: `${CREAR_CATEGORY_KEY}-${EVENTOS_SUBCATEGORY_KEY}`,
  crearObjetivos: `${CREAR_CATEGORY_KEY}-${OBJETIVOS_SUBCATEGORY_KEY}`,
  crearRegistros: `${CREAR_CATEGORY_KEY}-${REGISTROS_SUBCATEGORY_KEY}`,
  /* DE EDICION */
  editarRoles: `${EDITAR_CATEGORY_KEY}-${ROLES_SUBCATEGORY_KEY}`,
  editarUsuarios: `${EDITAR_CATEGORY_KEY}-${USUARIOS_SUBCATEGORY_KEY}`,
  editarClientes: `${EDITAR_CATEGORY_KEY}-${CLIENTES_SUBCATEGORY_KEY}`,
  editarNoticias: `${EDITAR_CATEGORY_KEY}-${NOTICIAS_SUBCATEGORY_KEY}`,
  editarHorarios: `${EDITAR_CATEGORY_KEY}-${HORARIOS_SUBCATEGORY_KEY}`,
  editarEventos: `${EDITAR_CATEGORY_KEY}-${EVENTOS_SUBCATEGORY_KEY}`,
  editarRegistros: `${EDITAR_CATEGORY_KEY}-${REGISTROS_SUBCATEGORY_KEY}`,
  /* DE ELIMINACION */
  eliminarRoles: `${ELIMINAR_CATEGORY_KEY}-${ROLES_SUBCATEGORY_KEY}`,
  eliminarClientes: `${ELIMINAR_CATEGORY_KEY}-${CLIENTES_SUBCATEGORY_KEY}`,
  eliminarUsuarios: `${ELIMINAR_CATEGORY_KEY}-${USUARIOS_SUBCATEGORY_KEY}`,
  eliminarNoticias: `${ELIMINAR_CATEGORY_KEY}-${NOTICIAS_SUBCATEGORY_KEY}`,
  eliminarApps: `${ELIMINAR_CATEGORY_KEY}-${APPS_SUBCATEGORY_KEY}`,
  eliminarHorarios: `${ELIMINAR_CATEGORY_KEY}-${HORARIOS_SUBCATEGORY_KEY}`,
  eliminarEventos: `${ELIMINAR_CATEGORY_KEY}-${EVENTOS_SUBCATEGORY_KEY}`,
  eliminarRegistros: `${ELIMINAR_CATEGORY_KEY}-${REGISTROS_SUBCATEGORY_KEY}`,
  /* DE INACTIVACIÓN */
  inactivarUsuarios: `${INACTIVAR_CATEGORY_KEY}-${USUARIOS_SUBCATEGORY_KEY}`,
  /* DE APROBACIÓN */
  aprobarVacaciones: `${APROBAR_CATEGORY_KEY}-${VACACIONES_SUBCATEGORY_KEY}`,
  /* PARA ASIGNACION DE REGISTROS */
  asignarRegistros: `${ASIGNAR_CATEGORY_KEY}-${REGISTROS_SUBCATEGORY_KEY}`,
  /* EVALUAR */
  evaluarObjetivos: `${EVALUAR_CATEGORY_KEY}-${OBJETIVOS_SUBCATEGORY_KEY}`
} as const;
