import {
  APPS_KEY,
  CLIENTES_KEY,
  EVENTOS_KEY,
  HORARIOS_KEY,
  NOTICIAS_KEY,
  OBJETIVOS_KEY,
  REGISTROS_KEY,
  REPORTES_KEY,
  ROLES_KEY,
  USUARIOS_KEY,
  VACACIONES_KEY
} from './keys';

/* CRUD CATEGORIES */
const ACCESO_CATEGORY_KEY = 'acceso';
const CREAR_CATEGORY_KEY = 'crear';
const EDITAR_CATEGORY_KEY = 'editar';
const ELIMINAR_CATEGORY_KEY = 'eliminar';
const INACTIVAR_CATEGORY_KEY = 'inactivar';
const APROBAR_CATEGORY_KEY = 'aprobar';
const ASIGNAR_CATEGORY_KEY = 'asignar';
const EVALUAR_CATEGORY_KEY = 'evaluar';
const PERSONALIZADOS_CATEGORY_KEY = 'personalizados';
/* FUNCTIONS SUBCATEGORIES */
const USUARIOS_SUBCATEGORY_KEY = USUARIOS_KEY;
const CLIENTES_SUBCATEGORY_KEY = CLIENTES_KEY;
const NOTICIAS_SUBCATEGORY_KEY = NOTICIAS_KEY;
const APPS_SUBCATEGORY_KEY = APPS_KEY;
const ROLES_SUBCATEGORY_KEY = ROLES_KEY;
const EVENTOS_SUBCATEGORY_KEY = EVENTOS_KEY;
const REPORTES_SUBCATEGORY_KEY = REPORTES_KEY;
const OBJETIVOS_SUBCATEGORY_KEY = OBJETIVOS_KEY;
const REGISTROS_SUBCATEGORY_KEY = REGISTROS_KEY;
const HORARIOS_SUBCATEGORY_KEY = HORARIOS_KEY;
const VACACIONES_SUBCATEGORY_KEY = VACACIONES_KEY;
const VERMISREGISTROS_SUBCATEGORY_KEY = 'ver-solo-mis-registros';

export const PERMISOS_MAP_IDS = {
  /* DE ACCESO */
  accesoRoles: `${ACCESO_CATEGORY_KEY}-${ROLES_SUBCATEGORY_KEY}`,
  accesoClientes: `${ACCESO_CATEGORY_KEY}-${CLIENTES_SUBCATEGORY_KEY}`,
  accesoUsuarios: `${ACCESO_CATEGORY_KEY}-${USUARIOS_SUBCATEGORY_KEY}`,
  accesoNoticias: `${ACCESO_CATEGORY_KEY}-${NOTICIAS_SUBCATEGORY_KEY}`,
  accesoApps: `${ACCESO_CATEGORY_KEY}-${APPS_SUBCATEGORY_KEY}`,
  accesoHorarios: `${ACCESO_CATEGORY_KEY}-${HORARIOS_SUBCATEGORY_KEY}`,
  accesoEventos: `${ACCESO_CATEGORY_KEY}-${EVENTOS_SUBCATEGORY_KEY}`,
  accesoVacaciones: `${ACCESO_CATEGORY_KEY}-${VACACIONES_SUBCATEGORY_KEY}`,
  accesoReportes: `${ACCESO_CATEGORY_KEY}-${REPORTES_SUBCATEGORY_KEY}`,
  accesoObjetivos: `${ACCESO_CATEGORY_KEY}-${OBJETIVOS_SUBCATEGORY_KEY}`,
  accesoRegistros: `${ACCESO_CATEGORY_KEY}-${REGISTROS_SUBCATEGORY_KEY}`,
  /* DE CREAR */
  crearUsuarios: `${CREAR_CATEGORY_KEY}-${USUARIOS_SUBCATEGORY_KEY}`,
  crearClientes: `${CREAR_CATEGORY_KEY}-${CLIENTES_SUBCATEGORY_KEY}`,
  crearRoles: `${CREAR_CATEGORY_KEY}-${ROLES_SUBCATEGORY_KEY}`,
  crearNoticias: `${CREAR_CATEGORY_KEY}-${NOTICIAS_SUBCATEGORY_KEY}`,
  crearApps: `${CREAR_CATEGORY_KEY}-${APPS_SUBCATEGORY_KEY}`,
  crearHorarios: `${CREAR_CATEGORY_KEY}-${HORARIOS_SUBCATEGORY_KEY}`,
  crearEventos: `${CREAR_CATEGORY_KEY}-${EVENTOS_SUBCATEGORY_KEY}`,
  crearObjetivos: `${CREAR_CATEGORY_KEY}-${OBJETIVOS_SUBCATEGORY_KEY}`,
  crearRegistros: `${CREAR_CATEGORY_KEY}-${REGISTROS_SUBCATEGORY_KEY}`,
  /* DE EDICION */
  editarRoles: `${EDITAR_CATEGORY_KEY}-${ROLES_SUBCATEGORY_KEY}`,
  editarUsuarios: `${EDITAR_CATEGORY_KEY}-${USUARIOS_SUBCATEGORY_KEY}`,
  editarClientes: `${EDITAR_CATEGORY_KEY}-${CLIENTES_SUBCATEGORY_KEY}`,
  editarNoticias: `${EDITAR_CATEGORY_KEY}-${NOTICIAS_SUBCATEGORY_KEY}`,
  editarHorarios: `${EDITAR_CATEGORY_KEY}-${HORARIOS_SUBCATEGORY_KEY}`,
  editarEventos: `${EDITAR_CATEGORY_KEY}-${EVENTOS_SUBCATEGORY_KEY}`,
  editarRegistros: `${EDITAR_CATEGORY_KEY}-${REGISTROS_SUBCATEGORY_KEY}`,
  /* DE ELIMINACION */
  eliminarRoles: `${ELIMINAR_CATEGORY_KEY}-${ROLES_SUBCATEGORY_KEY}`,
  eliminarClientes: `${ELIMINAR_CATEGORY_KEY}-${CLIENTES_SUBCATEGORY_KEY}`,
  eliminarUsuarios: `${ELIMINAR_CATEGORY_KEY}-${USUARIOS_SUBCATEGORY_KEY}`,
  eliminarNoticias: `${ELIMINAR_CATEGORY_KEY}-${NOTICIAS_SUBCATEGORY_KEY}`,
  eliminarApps: `${ELIMINAR_CATEGORY_KEY}-${APPS_SUBCATEGORY_KEY}`,
  eliminarHorarios: `${ELIMINAR_CATEGORY_KEY}-${HORARIOS_SUBCATEGORY_KEY}`,
  eliminarEventos: `${ELIMINAR_CATEGORY_KEY}-${EVENTOS_SUBCATEGORY_KEY}`,
  eliminarRegistros: `${ELIMINAR_CATEGORY_KEY}-${REGISTROS_SUBCATEGORY_KEY}`,
  /* DE INACTIVACIÓN */
  inactivarUsuarios: `${INACTIVAR_CATEGORY_KEY}-${USUARIOS_SUBCATEGORY_KEY}`,
  /* DE APROBACIÓN */
  aprobarVacaciones: `${APROBAR_CATEGORY_KEY}-${VACACIONES_SUBCATEGORY_KEY}`,
  /* PARA ASIGNACION DE REGISTROS */
  asignarRegistros: `${ASIGNAR_CATEGORY_KEY}-${REGISTROS_SUBCATEGORY_KEY}`,
  /* EVALUAR */
  evaluarObjetivos: `${EVALUAR_CATEGORY_KEY}-${OBJETIVOS_SUBCATEGORY_KEY}`,
  /* PERSONALIZADOS */
  verMisRegistros: `${PERSONALIZADOS_CATEGORY_KEY}-${VERMISREGISTROS_SUBCATEGORY_KEY}`
} as const;
