import {
  APPS_KEY,
  CLIENTES_KEY,
  DOMAIN_KEY,
  EVENTOS_KEY,
  HORARIOS_KEY,
  NOTICIAS_KEY,
  OBJETIVOS_KEY,
  PERMISOS_KEY,
  REGISTROS_KEY,
  ROLES_KEY,
  USER_KEY,
  USUARIOS_KEY,
  UTILITIES_KEY,
  VACACIONES_KEY
} from './keys';

export const SELECTED_ROW_NAME = 'selectedRow';
export const USER_NAME = USER_KEY;
export const USER_DOMAIN = `${USER_KEY}-${DOMAIN_KEY}`;
export const UTILITIES_NAME = UTILITIES_KEY;
export const ROLES_NAME = ROLES_KEY;
export const PERMISOS_NAME = PERMISOS_KEY;
export const USUARIOS_NAME = USUARIOS_KEY;
export const ROLES_PERMISOS_NAME = `${ROLES_NAME}-${PERMISOS_NAME}`;
export const CLIENTES_NAME = CLIENTES_KEY;
export const APPS_NAME = APPS_KEY;
export const EVENTOS_NAME = EVENTOS_KEY;
export const NOTICIAS_NAME = NOTICIAS_KEY;
export const OBJETIVOS_NAME = OBJETIVOS_KEY;
export const REGISTROS_NAME = REGISTROS_KEY;
export const HORARIOS_NAME = HORARIOS_KEY;
export const VACACIONES_NAME = VACACIONES_KEY;
